version: "3.8"
services:
    postgres:
        container_name: "workout-manager-program-postgres"
        image: postgres:15
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=workout_manager_programs
        volumes:
            - postgres_data_container:/var/lib/postgresql/data

volumes:
    postgres_data_container:
